# Generated by Django 4.2.16 on 2024-11-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='similarity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
