# Generated by Django 4.2.16 on 2024-11-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_hangmangame'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guess',
            new_name='Cemantix',
        ),
    ]
