# Generated by Django 4.2.16 on 2024-11-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_guess_cemantix'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HangmanGame',
            new_name='Hangman',
        ),
    ]
