# Generated by Django 4.2.16 on 2024-11-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_fallingenemygame'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FallingEnemyGame',
        ),
    ]
