# Generated by Django 4.2.16 on 2024-11-04 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_lock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lock',
            name='lives',
        ),
        migrations.RemoveField(
            model_name='lock',
            name='user',
        ),
    ]
