# Generated by Django 4.2.16 on 2024-11-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_lock_lives_remove_lock_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crossword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=5)),
                ('clue', models.CharField(max_length=255)),
            ],
        ),
    ]
